### ISSUE TITLE
Error 301 and 202

### ISSUE THREAD

**Issue by CyberMixRo** [YoannQueret/ODR-EncoderManager#10]
Hello,

I get this errors on 

1. Status:

Load status
ERROR = -301 : Error when getting ODR-audioencoder and ODR-padencoder status (XMLRPC): [Errno 111] Connection refused

2. Manage Encoder:

Write changes
ERROR = -202
Error generating supervisor files: list indices must be integers or slices, not str

Maybe missing some library to be installed but i follow your install instruction and run on Debian 9. What is missing? I see on config.json as have to run on port 8900 RPC2 witch is not happen and i don't see any error on logs

Thanks

**Comment by YoannQueret** [comment]
Hello,
About 1.Status, check your `/etc/supervisor/supervisord.conf`. `inet_http_server` section need to have same login/password as your `config.json` file under `global/supervisor_xmlrpc`

More globaly, can you try with next branch ?

**Comment by CyberMixRo** [comment]
Hello Yoann,

> Hello,
> About 1.Status, check your `/etc/supervisor/supervisord.conf`. `inet_http_server` section need to have same login/password as your `config.json` file under `global/supervisor_xmlrpc`
> 

Yes i check and are correct, but there is a confusion: on config.json.sample there is:
"supervisor_xmlrpc": "http://user:pass@127.0.0.1:8900/RPC2"

The supervisor run on port 9001 as you describe on installation detaiils:

[inet_http_server]
port = 9001
username = user ; Auth username
password = pass ; Auth password

Of corse even if i access in browser http://127.0.0.1:9001/RPC2 do not exist and port 8900 is not used by any application, is closed. 

My opinion is as i do not have XML-RPC on supervisor or the app do not open that. Can you give me some more information about what i have to check because honest i can not identify where is the problem, what is clear is as on port 9001 (where supervisor web interface run) i do not have /RCP2

Error response
Error code 404.

Message: Not Found.

> 

> More globaly, can you try with next branch ?

I try and i get many errors by pyton even if i have bot version of python 2 and 3. Is there another instruction or library to be installed?

Thanks

**Comment by YoannQueret** [comment]
If you use 
```
[inet_http_server]
port = 8900
username = user ; Auth username
password = pass ; Auth password
```
You have to set your config.json to `"supervisor_xmlrpc": "http://user:pass@127.0.0.1:8900/RPC2"`. If you change supervisor configuration, don't forget to restart it.

After you can acces supervisor interface via http://127.0.0.1:8900/

I push a new patch on next branch few min ago to solve issue when SBR and PS was disable.

**Comment by CyberMixRo** [comment]
I download last "next" branch and works all well till now. Thanks
