### ISSUE TITLE
mot fifo file instead file

### ISSUE THREAD

**Issue by YoannQueret** [YoannQueret/ODR-EncoderManager#2]
mot pad file is currently a file created before mot-encoder start. Need to create a FIFO file with mkfifo instead.

**Comment by mpbraendli** [comment]
dabplus-enc will create the pad fifo (dabplus-enc.cpp +538) if it doesn't exist yet. mot-encoder fails if the fifo doesn't exist.

Maybe this can allow you to skip manual creation of the fifo.

**Comment by YoannQueret** [comment]
issue solved in next branch
