### ISSUE TITLE
uniq_id needed to set DLS/DL+ via API for this encoder is ...

### ISSUE THREAD

**Issue by allegfede** [YoannQueret/ODR-EncoderManager#20]
hello, tried to set a new encoder in the manager, but the encoder quits with this message:

uniq_id needed to set DLS/DL+ via API for this encoder is :
6d3b344a-etc etc-fa4df99a05d6

where i have to set this key?

is there a manual or a wiki?

Thanks

**Comment by YoannQueret** [comment]
uniq_id is automatically set when you create an encoder.
This uniq_id is used everywhere, and also to setup DLS/DL+/SLS via API.

API documentation is available under Help > Help menu

**Comment by allegfede** [comment]
thanks for the kind answer. Thanks.
