### ISSUE TITLE
Could not open /tmp/metadata.dls

### ISSUE THREAD

**Issue by LyonelB** [YoannQueret/ODR-EncoderManager#5]
Bonjour,

Je teste actuellement ODR-EncoderManger avec un Raspberry et Raspbian Stretch Lite
Les logs de Padenc indique : 
```
...ODR-PadEnc exits...
ODR-PadEnc encoding DLS from '/tmp/metadata.dls' to '/tmp/metadata.pad'. No Slideshow.
ODR-PadEnc using charset UTF-8 (15)
ODR-PadEnc converting DLS texts to Complete EBU Latin
Could not open /tmp/metadata.dls
Could not open /tmp/metadata.dls
```
La commande ls -l /tmp renvoie : 
```
odr@raspberrypi:~ $ ls -l /tmp
total 0
prw-r--r-- 1 odr odr 0 Feb 19 09:39 metadata.pad
```
J'ai donc créé les fichiers : 
```
$ cd /tmp
$ mkdir slide && cd slide
$ wget http://url.de.mon.image.jpeg
$ cd /tmp
$ touch metadata.dls
```
Est-ce la bonne méthode ?

**Comment by YoannQueret** [comment]
Le fichier metadata.dls est normalement créé lors de l'application de la configuration sur l'onglet Configuration.
Il faut peut-etre mettre ce fichier à un autre endroit que dans /tmp/ qui peut être un tmpfs et donc être effacé a chaque redemarrage de l'OS.

**Comment by LyonelB** [comment]
Je viens de modifier la section "output" dans l'onglet Configuration : 

Slide directory: /tmpfs/slide/
PAD fifo file: /tmpfs/metadata.pad
DLS fifo file: /tmpfs/metadata.dls

J'ai l'erreure suivante : 

```
Write changes

ERROR = -202 : Error generating supervisor files('Error when create DLS fifo file', "[Errno 2] No such file or directory: u'/tmpfs/metadata.dls'")
```

**Comment by YoannQueret** [comment]
tmpfs est un RAMDisk, Le repertoire /tmp/ est souvent un tmpfs, c'est a dire qu'il n'est pas physiquement sur le disk mais en memoire. Lorsque l'OS redemarre il est effacé.

mkdir /pad/
chmod 777 /pad/
mkdir /pad/slide/
chmod 777 /pad/slide/

PAD fifo file: /pad/metadata.pad
DLS fifo file: /pad/metadata.dls
Slide directory : /pad/slide/

J'ai mis 777 pour les droits dans l'exemple, mais je te laisse adapter les users/groups et droits au beosin.

**Comment by LyonelB** [comment]
Second essai : 

Je viens de modifier la section "output" dans l'onglet Configuration :

Slide directory: /home/odr/tmpfs/slide/
PAD fifo file: /home/odr/tmpfs/metadata.pad
DLS fifo file: /home/odr/tmpfs/metadata.dls

Et là je n'ai plus d'erreur

**Comment by LyonelB** [comment]
Merci,

J'ai suivi tes indications et tout est ok.
