### ISSUE TITLE
No "Restart" button

### ISSUE THREAD

**Issue by LyonelB** [YoannQueret/ODR-EncoderManager#6]
J'ai modifié le fichier  /etc/sudoers en ajoutant la ligne suivante : 

`odr     ALL=(ALL) NOPASSWD: /sbin/shutdown`

Puis redemarré ODR-EncoderManger via supervisor, mais je n'ai pas de bouton Restart qui apparait sur l'interface

**Comment by YoannQueret** [comment]
Via l'interface : Tools > Network Mangement

Les issue de GitHub ne sont pas vraiment faire pour poser des questions sur l'utilisation mais pour remonter des bugs avérés.

**Comment by LyonelB** [comment]
Désolé mais je n'ai pas l'option "Network Management" :-( 
Dans le menu : 
Tools > Backup & Restore
         > User Management

**Comment by YoannQueret** [comment]
Le Network Management est activé quand dans le fichier de configuration json il y a la section network de renseignée sous la section global.
"network": {
            "cards": [
                {
                    "card": "eth0",
                    "alias": "CONFIG",
                    "manage": "true",
                    "dhcp": "false",
                    "ip": "192.168.0.1",
                    "netmask": "255.255.255.0",
                    "gateway": ""
                }
            ]

MAIS !!! comme c'est assez tricky niveau system pour que cette partie fonctionne, ce n'est pas activé par default.
